/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo {
    private val real: Int
    private val imaginario: Int

    fun inicializar(real: Int, imaginario: Int){
        this.real=real
        this.real=real
    }
}

fun main() {
    val c = Complejo(3.0, 4.0)
    println(c.mostrar())
    pirntln("hola")
}